#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly=TRUE)
url <- args[1]
if (Sys.getenv("ARTICLE_DIR") == "") {
    stop("Please set `ARTICLE_DIR`!")
}

## debug
## url <- "https://www.bild.de/regional/hamburg/hamburg-aktuell/soltau-auf-dem-weg-in-den-knast-nach-dem-pinkeln-schuettelte-er-die-polizisten-a-80708066.bild.html?wtmc=ob.feed"
## Sys.setenv("ARTICLE_DIR" = "~/dev/fodira/page_dl/html")

rD <- RSelenium::rsDriver(browser = "firefox", port = sample(c(5678L, 5679L, 5680L, 5681L, 5682L), size = 1), check = FALSE, verbose = FALSE)
remDr <- rD[["client"]]
remDr$navigate(url)
src <- remDr$getPageSource()

url_hash <- digest::sha1(url, digits = 40)

fname <- paste0(url_hash, "_" ,Sys.time(), ".html")

writeLines(src[[1]], file.path(Sys.getenv("ARTICLE_DIR"), fname))

remDr$close()
z <- rD$server$stop()
