#!/usr/bin/env Rscript

library(fodira)
args <- commandArgs(trailingOnly=TRUE)

OUTPUT_FILE <- "res.RDS"

## Zeit won't work
.get_urls <- function(con, safe) {
    if (safe) {
        con$aggregate('[ {"$match": {"htmlfile": "", "pub" : { "$in": ["Bild", "Tagesschau", "Heute", "Freitag", "T-Online"]}}}, { "$sample": { "size": 30} }]')$link
    } else {
        con$aggregate('[ {"$match": {"htmlfile": "", "pub": { "$nin": ["Zeit"]}}}, { "$sample": { "size": 30} }]')$link
    }
}

if (length(args) == 0) {
    urls <- readLines(file("stdin"))
} else if (args[1] == "db") {
    con <- mongolite::mongo("articles", db = "main")
    if (is.na(args[2])) {
        urls <- .get_urls(con, safe = FALSE)
    } else if (args[2] == "safe") {
        urls <- .get_urls(con, safe = TRUE)
    }
} else {
    urls <- args
}

if (Sys.getenv("ARTICLE_DIR") == "") {
    stop("Please set `ARTICLE_DIR`!")
}

res <- fodira::scrape(urls, verbose = TRUE)

saveRDS(res, OUTPUT_FILE)
