#!/usr/bin/env Rscript

library(fodira)

links_file <- fodira::request_links(size = 100)

urls <- readRDS(links_file)

current_temp <- tempdir()
output_dir <- file.path(current_temp, "html")

if (!dir.exists(output_dir)) {
    dir.create(output_dir)
}

res <- fodira::scrape(urls, verbose = TRUE, output_dir = output_dir)
output_rds <- file.path(current_temp, "output.RDS")
saveRDS(res, output_rds)
job_fname <- fodira::pack_work(file.path(current_temp, generate_hash(".tar.gz")), rds = output_rds, output_dir = output_dir, delete = TRUE)
fodira::submit_job(job_fname, verbose = TRUE)
