## test_that("test_insert", {
##     skip_on_ci()
##     tryCatch({
##         con <- mongolite::mongo(collection = "articles", db = "main", verbose = FALSE)
##     }, error = function(e) {
##         skip("No MongoDB")
##     })
##     mongolite::mongo("testthat", "main")$drop()
##     mongolite::mongo("htmltt", "main")$drop()
##     output <- readRDS("../testdata/output.RDS")
##     colnames(output) <- c("link", "fname")
##     output <- dplyr::bind_rows(output, tibble::tibble(link = "https://www.chainsawriot.com", fname = NA))
##     con <- mongolite::mongo(collection = "testthat", db = "main", verbose = FALSE)
##     con$insert(output[,c("link")])
##     expect_equal(0, nrow(con$find('{"htmlfile": {"$exists": 1}}')))
##     expect_equal(31, nrow(con$find('{}')))
##     tempfile <- tempfile(fileext = "tar.gz")
##     x <- file.copy("../testdata/test_job.tar.gz", tempfile)
##     push_html_job(tempfile, db = "main", collection = "testthat", prefix = "htmltt", delete = TRUE)
##     expect_false(0 == nrow(con$find('{"htmlfile": {"$exists": 1}}')))
##     expect_true(30 == nrow(con$find('{"htmlfile": {"$exists": 1}}')))
##     expect_true(1 == ncol(con$find('{"link": "https://www.chainsawriot.com"}')))
##     fs <- mongolite::gridfs(db = "main", prefix = "htmltt")
##     for (i in seq_len(30)) {
##         tmp <- tempfile()
##         expect_error(fs$read(output$fname[i], file(tmp), progress = FALSE), NA)
##         expect_error(readLines(tmp), NA)
##     }
##     mongolite::mongo("testthat", "main")$drop()
##     mongolite::mongo("htmltt", "main")$drop()
## })
