#!/usr/bin/env Rscript

## install.packages(c("tidyRSS", "purrr", "dplyr"))

args <- commandArgs(trailingOnly=TRUE)
csv <- args[2]
## for debug
##csv <- "rss_list.csv"

library(magrittr)
input <- rio::import(csv)

.silent_parse <- function(...) {
    suppressMessages(tidyRSS::tidyfeed(...))
}

res <- purrr::map(input$url, purrr::safely(.silent_parse))

res %>% purrr::discard(~!is.null(.$error)) %>% purrr::map("result") %>% purrr::map(~dplyr::select(., "feed_title", "item_link", "item_pub_date", "item_description")) %>% dplyr::bind_rows() -> valid_links

### failed feeds
## input$url[purrr::map_lgl(res, ~!is.null(.$error))]

## Should be inserted into a DB/redis or whatever
valid_links
