#!/usr/bin/env Rscript

## `links` should be a list of rds files with the standard format.
'Insert docdb-formated RDS file into the DB

Usage:
  insert <file> [--verbose] [--newlinks=<nl>]
  insert (-h | --help)
  insert (-v | --version)

Options:
  -h --help     Show this screen.
  -v --version     Show version.
  --newlinks=<nl>     Output file for new links [default: newlinks.RDS]
  --verbose     Display messages.

' -> doc

args <- docopt::docopt(doc, version = 'insert 0.0.3\n')

## args <- commandArgs(trailingOnly = TRUE)
## if ("debug" %in% args) {
##     debug <- TRUE
##     args <- setdiff(args, "debug")
## } else {
##     debug <- FALSE
## }

## if (length(args) == 0) {
##     link_files <- readLines(file("stdin"))
## } else {
##     link_files <- args
## }

.insert <- function(link_file, debug, newlinks_fname = "newlinks.RDS") {
    links <- fodira::harmonize_output(readRDS(link_file))
    newlinks <- fodira::insert_doc_link(links, debug = debug, db = "main", collection = "articles")
    if (!is.null(newlinks_fname)) {
        saveRDS(newlinks, newlinks_fname)
    }
    return(invisible(link_file))
}

.insert(link_file = args$file, debug = args$verbose, newlinks_fname = args$newlinks)
