#!/usr/bin/env Rscript

## `links` should be a list of rds files with the standard format.

args <- commandArgs(trailingOnly = TRUE)
if (length(args) == 0) {
    link_files <- readLines(file("stdin"))
} else {
    link_files <- args
}

## basically, it will only insert when the link is not already in ARTICLE_DB.
## Otherwise, it will not be inserted again.

.insert <- function(link_file) {
    link <- readRDS(link_file)
    db <- Sys.getenv("ARTICLE_DB")
    if (db == "") {
        stop("Please setup `ARTICLE_DB`!")
    }
    con <- DBI::dbConnect(duckdb::duckdb(), dbdir = db , read_only = FALSE)
    for (i in seq_len(nrow(link))) {
        existing_link <- DBI::dbGetQuery(con, "SELECT link FROM articles where link = ?", link[i, "link"])
        if (nrow(existing_link) == 0) {
            to_be_inserted <- as.data.frame(link[i,])
            if (lubridate::tz(to_be_inserted$pubdate) != "UTC") {
                to_be_inserted$pubdate <- lubridate::with_tz(to_be_inserted$pubdate, "UTC")
            }
            DBI::dbWriteTable(con, "articles", as.data.frame(link[i,]), append = TRUE)
        }
    }
    DBI::dbDisconnect(con, shutdown = TRUE)
    return(invisible(link_file))
}

purrr::walk(link_files, .insert)
